---
name: Lint Code Base
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.0.2

      - name: Lint Code Base
        uses: github/super-linter@v4.9.6
        env:
          VALIDATE_ENV: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
